-- Active: 1773160310343@@127.0.0.1@5432@magdan

CREATE USER partner WITH PASSWORD 'MagDan-P3';
GRANT ALL PRIVILEGES ON DATABASE magdan TO partner;

GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO partner;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO partner;
GRANT ALL PRIVILEGES ON ALL FUNCTIONS IN SCHEMA public TO partner;

ALTER DEFAULT PRIVILEGES IN SCHEMA public
GRANT ALL PRIVILEGES ON TABLES TO partner;

ALTER DEFAULT PRIVILEGES IN SCHEMA public
GRANT ALL PRIVILEGES ON SEQUENCES TO partner;

ALTER DEFAULT PRIVILEGES IN SCHEMA public
GRANT ALL PRIVILEGES ON FUNCTIONS TO partner;
